# Importing Numpy

In [5]:
#Import numpy 
import numpy as np

# sys was imported to check the python version
import sys
# check the version of python and NumPy
print('NumPy version:', np.__version__)
print('Python version',sys.version)

NumPy version: 1.16.2
Python version 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)]


# How to create NumPy arrays

In [28]:
# Create one dimensional NumPy array
np.array([1, 2, 3])

array([1, 2, 3])

In [4]:
# Array of zeros
np.zeros(3)

array([0., 0., 0.])

In [5]:
# Array of 1s
np.ones(3)

array([1., 1., 1.])

In [93]:
# Create a constant array
c = np.full((4,4), 5)  
print(c) 

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [89]:
# Create a 2x2 identity matrix
d = np.eye(5)
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
#Array of 3 random integers between 1 and 10
np.random.randint(1,10, size=3)

array([3, 2, 1])

In [23]:
# Create linearly spaced array
np.linspace(0, 10, 5, endpoint = True, retstep = False)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [26]:
# Create 2-dimensional array
np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
# Create 3x4 array values between 0 and 1
np.random.random((3,4))

array([[0.061689  , 0.26294795, 0.71141713, 0.31684676],
       [0.20849741, 0.86471957, 0.5505939 , 0.69298921],
       [0.99165857, 0.27026279, 0.34013508, 0.20517295]])

In [31]:
a = np.array([1,2,3])
b = np.random.randint(0,10, (3,3))

print(a)
print(b)

[1 2 3]
[[5 6 5]
 [5 8 8]
 [4 8 9]]


In [32]:
# Adding new values into the the array
a = np.append(a, 4)
a

array([1, 2, 3, 4])

In [33]:
# Print the shape and dimension of arrays
print("Shape of a:", np.shape(a))
print("Shape of b:", np.shape(b))
print('Dimension of a:', np.ndim(a))
print('Dimension of b:', np.ndim(b))

Shape of a: (4,)
Shape of b: (3, 3)
Dimension of a: 1
Dimension of b: 2


In [34]:
# Number of elements in the arrays
print('Number of elements in a:', np.size(a))
print('Number of elements in b:', np.size(b))

Number of elements in a: 4
Number of elements in b: 9


# Indexing and Fancy Indexing

In [42]:
# a is 1D array, we created before
# b is 2D array, we created before
print(a)
print(b)

[1 2 3 4]
[[5 6 5]
 [5 8 8]
 [4 8 9]]


In [50]:
# Get the first element of a 
# These two print statements generate the same result
print(a[0])
print(a[-4])

(4,)
1
1


In [45]:
# Get the last element of a 
# These two print statements generate the same result
print(a[-1]) 
print(a[3])

4
4


In [51]:
# Get the first row of b
# These two print statements generate the same result
print(b[0]) 
print(b[0,:])

[5 6 5]
[5 6 5]


In [53]:
# Get the second column of b
b[:,1]

array([6, 8, 8])

In [7]:
# To understand the fancy indexing better we will create two new arrays. 
x = np.array(['a', 'b', 'c'])
y = np.array([['d', 'e', 'f'], 
              ['g', 'h', 'k']])
print(x)
print(y)

['a' 'b' 'c']
[['d' 'e' 'f']
 ['g' 'h' 'k']]


In [57]:
# Fancy indexing on 1-D array
# Get the value of c in array x
ind = [1,1]
y[ind]

array([['g', 'h', 'k'],
       ['g', 'h', 'k']], dtype='<U1')

In [8]:
# Fancy indexing on 2D array
# Get the values e, h in array y
row=np.array([0,1])
col=np.array([1,1])
y[row, col]

array(['e', 'h'], dtype='<U1')

In [14]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
b = np.array([0, 2, 0, 1])
print(a)
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[0 2 0 1]


In [15]:
print(a[np.arange(4), b])


[ 1  6  7 11]


In [20]:
a[np.arange(4), b] += 10

# Boolean Array Indexing

In [22]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [27]:
# Find the elements of a that are bigger than 2;
bool_idx = (a > 2)
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [29]:
# We use boolean array indexing to construct a rank 1 array consisting of the elements of a corresponding to the True values of bool_idx
print(a[bool_idx])
print(a[a > 2]) 

[3 4 5 6]
[3 4 5 6]


# Slicing

In [75]:
# Create an array of integers from 1 to 10
X = np.arange(1, 11, dtype=int)
X

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
# Get the first two elements of X 
X[:2]

array([1, 2])

In [77]:
# Get the number 3,4 and 5 
X[2:5]

array([3, 4, 5])

In [78]:
# Get odd numbers 
X[::2]

array([1, 3, 5, 7, 9])

In [81]:
# Get even numbers
X[1::2]

array([ 2,  4,  6,  8, 10])

In [82]:
# Create 2-D array 
Y= np.arange(1,10).reshape(3,3)
Y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
# Get the first and second row
Y[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
# Get the second and third column
Y[:, 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [85]:
# Get the element of 5 and 6
Y[1,1:]

array([5, 6])

# Universal Functions (Ufuncs)

In [96]:
# Find the maximum element of X
np.max(X)


10

In [97]:
# Mean of values in the X
np.mean(X)

5.5

In [99]:
#Get the 4th power of each element in X
np.power(X, 4)

array([    1,    16,    81,   256,   625,  1296,  2401,  4096,  6561,
       10000], dtype=int32)

In [100]:
# Trigonometric functions 
print(np.sin(X))
print(np.tan(X))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619
  0.87144798 -6.79971146 -0.45231566  0.64836083]


In [101]:
# (sinx)2 + (cosy)2 = 1 famous trigonometric equation
np.square(np.sin(X)) + np.square(np.cos(X))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [102]:
# array Y created before
Y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [103]:
# The same rules apply for 2-D arrays
np.multiply(Y, 2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [104]:
# split Y into 3 subarrays
np.split(Y, 3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

# Broadcasting

In [105]:
# Add 5 to each element of X
X + 5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [106]:
# Or 
np.add(X, 5)

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [107]:
# Create new array Z 
Z = np.arange(3)[:, np.newaxis]
Z

array([[0],
       [1],
       [2]])

In [108]:
# Multiple Y and Z
np.multiply(Y, Z)

array([[ 0,  0,  0],
       [ 4,  5,  6],
       [14, 16, 18]])

# Masking, Comparing and Sorting

In [109]:
# Create an array of 10 elements between 1 and 5
x = np.random.randint(1,5, 10)
x

array([1, 3, 3, 4, 4, 1, 3, 3, 1, 4])

In [110]:
# Create (3,3) size of array elements from 1 and 5
y = np.random.randint(1,5, (3,3))
y

array([[1, 2, 3],
       [4, 3, 4],
       [1, 1, 2]])

In [111]:
# Sort elements in array x
np.sort(x)

array([1, 1, 1, 3, 3, 3, 3, 4, 4, 4])

In [112]:
# Sort values along the rows
np.sort(y, axis=0)

array([[1, 1, 2],
       [1, 2, 3],
       [4, 3, 4]])

In [113]:
# Sort values along the columns
np.sort(y, axis=1)

array([[1, 2, 3],
       [3, 4, 4],
       [1, 1, 2]])

In [114]:
# == , !=, < , >, >=, <= operations on arrays
# This returns a Boolean
x > 3

array([False, False, False,  True,  True, False, False, False, False,
        True])

In [115]:
# Use masking feature to get the values of comparisons
x[x>3]

array([4, 4, 4])

In [116]:
# Another example 
x[(x <= 3) & ( x > 1 )]

array([3, 3, 3, 3])

# https://cs231n.github.io/python-numpy-tutorial/#numpy

# https://datascientistnotebook.com/numpy/

# https://numpy.org/devdocs/user/quickstart.html